POST http://localhost:3000/api/v1/users
content-type: application/json

{
    "username": "Test User",
    "email": "testuser@teste.com",
    "password": "password123"
}

###
POST http://localhost:3000/api/v1/sessions
content-type: application/json

{
    "email": "testuser@teste.com",
    "password": "password123"
}

###
GET http://localhost:3000/api/v1/user



###
DELETE  http://localhost:3000/api/v1/sessions 

###
PATCH  http://localhost:3000/api/v1/activations/0226ba78-9afb-4ff5-b0b2-db7e3a5d3cb8