POST http://localhost:3000/api/v1/users
content-type: application/json

{
    "username": "agora vai",
    "email": "agpravai@teste.com",
    "password": "password123"
}

###
POST http://localhost:3000/api/v1/sessions
content-type: application/json

{
    "email": "testuser@teste.com",
    "password": "password123"
}

###
GET http://localhost:3000/api/v1/user



###
DELETE  http://localhost:3000/api/v1/sessions 

###
PATCH  http://localhost:3000/api/v1/activations/209d673d-2746-4ef8-a3a5-efe08eb9fccd