POST http://localhost:3000/api/v1/users
content-type: application/json

{
    "username": "oi oi ",
    "email": "teste@teste.com",
    "password": "password123"
}

###
POST http://localhost:3000/api/v1/sessions
content-type: application/json

{
    "email": "teste@teste.com",
    "password": "password123"
}

###
GET http://localhost:3000/api/v1/user



###
DELETE  http://localhost:3000/api/v1/sessions 

###
PATCH  http://localhost:3000/api/v1/activations/3fcfc2fd-bdc3-405a-a163-3d11a541593c